version: "3"

services:

  sae_wa:
    build:
      context: .
      dockerfile: Dockerfile
    image: sae_wa
    container_name: sae_wa
    restart: always
    env_file:
      - .env
    ports:
      - "4173:4173"
    networks:
      nodes-networks:
        aliases:
          - sae_wa

networks:
  nodes-networks:
    external: true